spring:
  application:
    name: MarsAI
server:
  port: 8081
  servlet:
    context-path: /api

# LangChain4j 配置
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ${DASHSCOPE_API_KEY:YOUR_API_KEY_HERE}

# AI 配置
ai:
  # 大模型 API 配置
  api-key: ${DASHSCOPE_API_KEY:YOUR_API_KEY_HERE}
  api-url: ${AI_API_URL:https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions}

# 高德地图配置
amap:
  maps-api-key: ${AMAP_MAPS_API_KEY:YOUR_AMAP_MAPS_API_KEY}
  web-api-key: ${AMAP_WEB_API_KEY:YOUR_AMAP_WEB_API_KEY}
  security-js-code: ${AMAP_SECURITY_JS_CODE:YOUR_AMAP_SECURITY_JS_CODE}

# MCP 配置
mcp:
  gaode:
    enabled: ${MCP_GAODE_ENABLED:true}

# 讯飞语音识别配置
asr:
  xfyun:
    app-id: ${XFYUN_APP_ID:YOUR_XFYUN_APP_ID}
    access-key-id: ${XFYUN_ACCESS_KEY_ID:YOUR_XFYUN_ACCESS_KEY_ID}
    access-key-secret: ${XFYUN_ACCESS_KEY_SECRET:YOUR_XFYUN_ACCESS_KEY_SECRET}


