spring:
  application:
    name: MarsAI
server:
  port: 8081
  servlet:
    context-path: /api

# LangChain4j 配置
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ${DASHSCOPE_API_KEY:sk-364aaac41e084a868ed16c41e9473e42}
      streaming-chat-model:
        model-name: qwen-max
        api-key: ${DASHSCOPE_API_KEY:<Your API Key>}
      embedding-model:
        model-name: text-embedding-v3

# AI 配置
ai:
  # 大模型 API 配置
  api-key: ${DASHSCOPE_API_KEY:sk-364aaac41e084a868ed16c41e9473e42}
  api-url: ${AI_API_URL:https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions}

# 高德地图配置
amap:
  maps-api-key: ${AMAP_MAPS_API_KEY:9561f121929a1b9d992150ad8746f16b}
  web-api-key: ${AMAP_WEB_API_KEY:7ce7be0fbc824997793aaf5c6f6005dc}
  security-js-code: ${AMAP_SECURITY_JS_CODE:d32844a5ef2ed1dce96e7d683a17fe49}

# 百度地图配置
baidu-map:
  ak: ${BAIDU_MAP_API_KEY:M2bHjBtPzNYIPLipc28ZRK1TZObg7k3U}

# MCP 配置
mcp:
  gaode:
    enabled: ${MCP_GAODE_ENABLED:true}
  baidu:
    enabled: ${MCP_BAIDU_ENABLED:false}

# 讯飞语音识别配置
asr:
  xfyun:
    app-id: ${XFYUN_APP_ID:4aeb1706}
    access-key-id: ${XFYUN_ACCESS_KEY_ID:2c63c56fc9dee8f89ea98f5fa23f57c5}
    access-key-secret: ${XFYUN_ACCESS_KEY_SECRET:ZjA2MDNkOWU1ZTEwNzgxOGE5NDZkNTMz}


